### ISSUE TITLE
hovering over links

### ISSUE THREAD

**Issue by neilcode** [jellysalmon/jellysalmon.github.io#1]
Hey Joey!

I like how your site is coming together. Thought I'd share this little trick I learned:

Your navigation bar includes a bit of code that makes link text large when you hover the mouse over it, I find it a bit jarring because the change of font size is so abrupt. If you add this to your styles.css, you might like the result:

a.darktext {
transition-duration: .5s;
}

Makes everything happen smooth and slick looking!

Cheers,
Neil

**Comment by jellysalmon** [comment]
Whoaaa. That's really cool! Thanks Neil! I'll definitely add it on in my next update.
